### ISSUE TITLE
python my_plugin.py fails

### ISSUE THREAD

**Issue by adxsoft** [hiway/logseq-python-plugin#4]
Installed as per instructions on Mac OS High Sierra

Get this error

logseq-python-plugin/src/logspyq/server/server.py", line 94, in _run
    uvconfig = uvicorn.config.Config(
TypeError: Config.__init__() got an unexpected keyword argument 'debug'

**Comment by hiway** [comment]
Thank you! And apologies, I have been away from computing for a while, and only now got around to fixing this bug.
